### ISSUE TITLE
custom namespace settings

### ISSUE THREAD

**Issue by venkatakondaveti** [namecheap/node-vault-client#22]
Hi Team,

First of all thanks. I'm trying to use this library and connect to vault for a custom namespace rather than default (root) namespace using aws IAM Auth. 

But looks like it's always trying to connect to ROOT namespace. Cant find the any vars/config to set namespace as parameter during client initialisation.

If I create a same aws IAM auth role in ROOT namespace it works.

Am I missing anything here or could someone please redirect me to the right settings for this. Thanks.

**Comment by mh377** [comment]
I have created a pull request to set an X-Vault-Namespace header that can be configured with a new namespace config property

https://github.com/namecheap/node-vault-client/pull/23/commits/6de107188d23a7fc754c0857fd3fa14a34b08c75


` VaultClient.boot('main', {
        api: { url: VAULT_ADDR },
        auth: {
            type: 'iam',
            mount: 'some_other_aws_mount_point',          // Optional
            config: {
                role: 'my_iam_role',
                iam_server_id_header_value: VAULT_ADDR,   // Optional
                namespace: 'some_namespace',              // Optional
                credentials: new AWS.Credentials({
                 accessKeyId: AWS_ACCESS_KEY,
                  secretAccessKey: AWS_SECRET_KEY,
                })
            }
        }
    })`

**Comment by b1ff** [comment]
0.6.0 is published with the updates from @mh377
